---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-vault-sa
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: db-vault-backend
spec:
  provider:
    vault:
      server: "http://hashicorp-vault.vault.svc.cluster.local:8200"
      path: "platform"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "databases-role"
          serviceAccountRef:
            name: "db-vault-sa"
