apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: shared-services-vault-backend
    kind: ClusterSecretStore
  target:
    name: pgadmin-secret
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: pgadmin
        property: email
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: pgadmin
        property: password
