apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.gitlab.io"
    chart: gitlab-runner
    targetRevision: 0.86.0
    helm:
      values: |
        gitlabUrl: "http://gitlab-service.gitlab.svc.cluster.local"
        runnerToken: "glrt-ByuiPxE5MCSuSxLxxgy5"
        rbac:
          create: true
        runners:
          config: |
            [[runners]]
            clone_url = "http://gitlab-service.gitlab.svc.cluster.local"
              
              environment = [
                "CI_SERVER_URL=http://gitlab-service.gitlab.svc.cluster.local" 
              ]

              [runners.kubernetes]
                namespace = "gitlab"
                image = "ubuntu:22.04"
                privileged = false
                
              [runners.custom_build_dir]
              [runners.cache]
              [runners.machine]
              [runners.kubernetes.pod_labels]
              [runners.kubernetes.pod_annotations]
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
