apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow

    p, role:developer, applications, get, workloads/*, allow
    p, role:developer, applications, sync, workloads/*, allow
    p, role:developer, applications, update, workloads/*, allow
    p, role:developer, applications, action/*, workloads/*, allow

    p, role:viewer, applications, get, */*, allow
    p, role:viewer, clusters, get, *, allow
    p, role:viewer, repositories, get, *, allow
    p, role:viewer, projects, get, *, allow

    g, nagih, role:admin
    g, hoanggxyuuki, role:developer
    g, nghuytan, role:developer
    g, lucastran05, role:developer
    g, kkevin, role:viewer
  policy.default: role:readonly
