virtual_machines:
  k8s-master:
    id: 201
    name: "k8s-master"
    node: "nagih"
    scsi_hardware: "virtio-scsi-single"

    template_id: 9001

    cpu: 2
    memory: 4096
    disks:
      - datastore_id: "local-lvm"
        interface: "scsi0"
        size: 20
        file_format: "raw"
        discard: "on"
        ssd: true

    dns:
      - "8.8.8.8"
      - "1.1.1.1"

    ip_config:
      address: "192.168.1.201/24"
      gateway: "192.168.1.1"

    user:
      username: "nagih"
      keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB5zy0044P9cHpQ9zhu3wdnGzPrYIeVHavdd3sxeopHU vuongmanhnghia@gmail.com"
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcAhDKqQubrgkHLasQ7IYnLR5v45TkXw2FJ3o5rPBgL vuongmanhnghia@gmail.com"

  k8s-worker-1:
    id: 211
    name: "k8s-worker-1"
    node: "nagih"
    scsi_hardware: "virtio-scsi-single"

    template_id: 9001

    cpu: 4
    memory: 8192
    disks:
      - datastore_id: "local-lvm"
        interface: "scsi0"
        size: 100
        file_format: "raw"
        discard: "on"
        ssd: true
      - datastore_id: "hdd-storage"
        interface: "scsi1"
        size: 100
        file_format: "qcow2"
        discard: "on"

    dns:
      - "8.8.8.8"
      - "1.1.1.1"

    ip_config:
      address: "192.168.1.211/24"
      gateway: "192.168.1.1"

    user:
      username: "nagih"
      keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB5zy0044P9cHpQ9zhu3wdnGzPrYIeVHavdd3sxeopHU vuongmanhnghia@gmail.com"
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcAhDKqQubrgkHLasQ7IYnLR5v45TkXw2FJ3o5rPBgL vuongmanhnghia@gmail.com"

  minecraft-server:
    id: 501
    name: "minecraft-server"
    node: "nagih"
    scsi_hardware: "virtio-scsi-single"

    template_id: 9001

    cpu: 4
    memory: 6144
    disks:
      - datastore_id: "local-lvm"
        interface: "scsi0"
        size: 50
        file_format: "raw"
        discard: "on"
        ssd: true
      - datastore_id: "hdd-storage"
        interface: "scsi1"
        size: 100
        file_format: "qcow2"
        discard: "on"

    dns:
      - "8.8.8.8"
      - "1.1.1.1"

    ip_config:
      address: "192.168.1.51/24"
      gateway: "192.168.1.1"

    user:
      username: "nagih"
      keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB5zy0044P9cHpQ9zhu3wdnGzPrYIeVHavdd3sxeopHU vuongmanhnghia@gmail.com"
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcAhDKqQubrgkHLasQ7IYnLR5v45TkXw2FJ3o5rPBgL vuongmanhnghia@gmail.com"

  david:
    id: 602
    name: "david"
    node: "nagih"
    scsi_hardware: "virtio-scsi-single"

    template_id: 9000

    cpu: 2
    memory: 4096
    disks:
      - datastore_id: "local-lvm"
        interface: "scsi0"
        size: 30
        file_format: "raw"
        discard: "on"
        ssd: true

    dns:
      - "8.8.8.8"
      - "1.1.1.1"

    ip_config:
      address: "192.168.1.62/24"
      gateway: "192.168.1.1"

    user:
      username: "david"
      keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPm/jank+if691bXnVDX3shVAo/whFvBBb+GJdyAt5+t datlht3@fpt.com"

  darwin:
    id: 603
    name: "darwin"
    node: "nagih"
    scsi_hardware: "virtio-scsi-single"

    template_id: 9000

    cpu: 2
    memory: 4096
    disks:
      - datastore_id: "local-lvm"
        interface: "scsi0"
        size: 30
        file_format: "raw"
        discard: "on"
        ssd: true

    dns:
      - "8.8.8.8"
      - "1.1.1.1"

    ip_config:
      address: "192.168.1.63/24"
      gateway: "192.168.1.1"

    user:
      username: "darwin"
      keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDtdlKk+03CjY0dePqsf8WhNeE7QeIpYe0+arF5+mwkh tungnt106@fpt.com"

  master:
    id: 604
    name: "master"
    node: "nagih"
    scsi_hardware: "virtio-scsi-single"

    template_id: 9000

    cpu: 2
    memory: 6144
    disks:
      - datastore_id: "local-lvm"
        interface: "scsi0"
        size: 40
        file_format: "raw"
        discard: "on"
        ssd: true

    dns:
      - "8.8.8.8"
      - "1.1.1.1"

    ip_config:
      address: "192.168.1.64/24"
      gateway: "192.168.1.1"

    user:
      username: "david"
      keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPm/jank+if691bXnVDX3shVAo/whFvBBb+GJdyAt5+t datlht3@fpt.com"

  kiendt:
    id: 605
    name: "kiendt"
    node: "nagih"
    scsi_hardware: "virtio-scsi-single"

    template_id: 9000

    cpu: 1
    memory: 2048
    disks:
      - datastore_id: "local-lvm"
        interface: "scsi0"
        size: 30
        file_format: "raw"
        discard: "on"
        ssd: true

    dns:
      - "8.8.8.8"
      - "1.1.1.1"

    ip_config:
      address: "192.168.1.65/24"
      gateway: "192.168.1.1"

    user:
      username: "kiendt"
      keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPKl+/2WQIcidE3bMa0byEY/49UjA9ufI3+ybWhl5FiT admin@DESKTOP-PRQ4TMA"

  hieuvu:
    id: 606
    name: "hieuvu"
    node: "nagih"
    scsi_hardware: "virtio-scsi-single"

    template_id: 9000

    cpu: 1
    memory: 4096
    disks:
      - datastore_id: "local-lvm"
        interface: "scsi0"
        size: 20
        file_format: "raw"
        discard: "on"
        ssd: true

    dns:
      - "8.8.8.8"
      - "1.1.1.1"

    ip_config:
      address: "192.168.1.66/24"
      gateway: "192.168.1.1"

    user:
      username: "hieuvu"
      keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKNzB14iW42D6K2y1+UZvhz52vWFsdJg7i5vBxSEd3By hainam@MSI"
