apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dmb-es
  namespace: discord-bots
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: ms-vault-backend
    kind: SecretStore
  target:
    name: dmb-secret
  dataFrom:
    - extract:
        key: discord-music-bot
