apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: music-bot-es
  namespace: discord-bots
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: discord-vault-backend
    kind: SecretStore
  target:
    name: music-bot-secret
  dataFrom:
    - extract:
        key: standalone/discord-bots/shared
