---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: shared-services
data:
  init.sql: |
    # CREATE USER auth_user WITH PASSWORD 'auth_password_123';
    # CREATE DATABASE auth_db OWNER auth_user;
    #
    # CREATE USER order_user WITH PASSWORD 'order_password_123';
    # CREATE DATABASE order_db OWNER order_user;
