---
apiVersion: v1
kind: Service
metadata:
  name: shared-postgres-service
  namespace: shared-services
spec:
  type: ClusterIP
  selector:
    app: shared-postgres
  ports:
    - port: 5432
      targetPort: 5432
