apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-secret
  namespace: cloudflare
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infra-vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-ddns-secret
  data:
    - secretKey: API_KEY
      remoteRef:
        key: cloudflare
        property: ddns_api_key
