---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-vault-sa
  namespace: microservices
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ms-vault-backend
  namespace: microservices
spec:
  provider:
    vault:
      server: "http://hashicorp-vault.vault.svc.cluster.local:8200"
      path: "workloads"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "microservices-role"
          serviceAccountRef:
            name: "ms-vault-sa"
