---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.27.0
    helm:
      parameters:
        - name: "server.dev.enabled"
          value: "true" # Bật Dev mode cho Homelab để bypass công đoạn Unseal phức tạp ban đầu
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ingress
  namespace: vault
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vault.nooblearn2code.com`)
      kind: Rule
      services:
        - name: hashicorp-vault
          port: 8200
