- name: Deploy GitLab on K8s
  delegate_to: localhost
  become: false
  block:
    - name: Deploy GitLab StatefulSet
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: gitlab
            namespace: "{{ gitlab_namespace }}"
          spec:
            serviceName: gitlab-service
            replicas: 1
            selector:
              matchLabels:
                app: gitlab
            template:
              metadata:
                labels:
                  app: gitlab
              spec:
                containers:
                - name: gitlab
                  image: gitlab/gitlab-ce:{{ gitlab_version }}
                  imagePullPolicy: IfNotPresent
                  env:
                  - name: GITLAB_OMNIBUS_CONFIG
                    value: "from_file '/etc/gitlab/gitlab.rb'"
                  ports:
                  - containerPort: 80
                    name: http
                  - containerPort: 22
                    name: ssh
                  volumeMounts:
                  - name: gitlab-config
                    mountPath: /etc/gitlab
                  - name: gitlab-data
                    mountPath: /var/opt/gitlab
                  - name: dshm
                    mountPath: /dev/shm
                volumes:
                - name: gitlab-config
                  persistentVolumeClaim:
                    claimName: gitlab-config-pvc
                - name: gitlab-data
                  persistentVolumeClaim:
                    claimName: gitlab-data-pvc
                - name: dshm
                  emptyDir:
                    medium: Memory
                    sizeLimit: 256Mi
