---
- name: Deploy GitLab Runner on K3s
  delegate_to: localhost
  become: false
  tags: k8s-runner
  block:
    - name: Deploy GitLab Runner via Helm
      kubernetes.core.helm:
        name: gitlab-runner
        chart_ref: gitlab-runner # Bỏ chữ "gitlab/" đi
        chart_repo_url: https://charts.gitlab.io # Thêm dòng này để tải thẳng từ source
        release_namespace: gitlab
        create_namespace: false
        update_repo_cache: yes
        values:
          gitlabUrl: "https://gitlab.nooblearn2code.com"
          runnerToken: "{{ gitlab_runner_token }}"
          rbac:
            create: true
          runners:
            config: |
              [[runners]]
                [runners.kubernetes]
                  namespace = "gitlab"
                  image = "ubuntu:22.04"
                  privileged = true
