apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shared-redis-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: shared-services-vault-backend
    kind: ClusterSecretStore
  target:
    name: shared-redis-secret
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis
        property: password
