---
- hosts: all
  become: true
  roles: [{ role: bootstrap, tags: bootstrap }]

- hosts: minecraft-server
  become: true
  roles:
    - { role: docker, tags: docker }
    - { role: minecraft, tags: minecraft }

- name: Setup K8s Cluster
  hosts: k8s_cluster
  tags: k8s-cluster
  roles: [{ role: k8s_prerequisite, tags: k8s-pre }]

- name: Setup K3s Control Plane
  hosts: k8s_master
  tags: k8s-cluster
  roles: [{ role: k8s_master, tags: k8s-master }]

- name: Setup K3s Workers
  hosts: k8s_worker
  tags: k8s-cluster
  roles: [{ role: k8s_worker, tags: k8s-worker }]

- name: Deploy Services to K8s
  hosts: k8s_master
  tags: k8s-deploy
  roles:
    - { role: k8s_bootstrap, tags: k8s-bootstrap }
    - { role: k8s_addons, tags: k8s-addons }
    - { role: k8s_postgres, tags: k8s-postgres }
