apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# THE SRE MAGIC: This prefixes EVERY resource and automatically updates internal links!
namePrefix: bot-1-
namespace: discord-bots

resources:
  - ../../base # Pull in the core deployment logic
  - external-secret.yml # Add the specific Vault secret
