apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yml
- deployment.yml
- service.yml
- ingress.yml

commonLabels:
  app: workflows
  tier: frontent

images:
- name: nooblearn2code/workflows
  newName: nooblearn2code/workflows
  newTag: 91fcbe88
