apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - ingress.yml
  - external-secret.yml

commonLabels:
  app: esl-service
  tier: backend
# configMapGenerator:
#   - name: esl-server-config
#     files:
#       - production.yaml=configs/production.yaml
