---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shared-postgres-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: shared-services-vault-backend
    kind: ClusterSecretStore
  target:
    name: shared-postgres-secret
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres
        property: user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres
        property: password
