apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ms-vault-backend
spec:
  provider:
    vault:
      server: "http://hashicorp-vault.vault.svc.cluster.local:8200"
      path: "apps"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "ms-role"
          serviceAccountRef:
            name: "ms-vault-sa"
