apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: db-vault-backend
    kind: SecretStore
  target:
    name: pgadmin-secret
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: databases/pgadmin
        property: admin_email
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: databases/pgadmin
        property: admin_password
