apiVersion: v1
kind: ServiceAccount
metadata:
  name: shared-vault-sa
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: shared-vault-backend
spec:
  provider:
    vault:
      server: "http://hashicorp-vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "shared-microservices-role"
          serviceAccountRef:
            name: "shared-vault-sa"
