---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-admin-sa
  namespace: vault

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-secret-destroyer
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "delete"] # Quyền lực sinh sát: Chỉ được xóa Secret

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-admin-sa-binding
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault-admin-sa
    namespace: vault
roleRef:
  kind: Role
  name: vault-secret-destroyer
  apiGroup: rbac.authorization.k8s.io
