---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: third-party-vault-sa
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vaultwarden-vault-backend
spec:
  provider:
    vault:
      server: "http://hashicorp-vault.vault.svc.cluster.local:8200"
      path: "workloads"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "third-party-role"
          serviceAccountRef:
            name: "third-party-vault-sa"
