apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uniquizz-api-es
  namespace: microservices
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: ms-vault-backend
    kind: SecretStore
  target:
    name: uniquizz-api-secret
  dataFrom:
    - extract:
        key: microservices/uniquizz/api
