apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-microservices
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/nagih7/homelab-gitops.git"
    targetRevision: main
    path: argocd-apps
    directory:
      recurse: true
      exclude: "root-*.yml"
      include: "*.yml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
