---
- name: MetalLB Configuration
  include_tasks: metallb.yml

- name: Traefik Configuration
  include_tasks: traefik.yml
  tags: k8s-traefik

- name: Cloudflare Tunnel Configuration
  include_tasks: cf_tunnel.yml
  tags: k8s-tunnel
