apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: seafile-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: seafile-vault-backend
    kind: SecretStore
  target:
    name: seafile-secret
  data:
    - secretKey: db_password
      remoteRef:
        key: third-party/seafile
        property: db_password

    - secretKey: admin_email
      remoteRef:
        key: third-party/seafile
        property: admin_email

    - secretKey: admin_password
      remoteRef:
        key: third-party/seafile
        property: admin_email
