apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cf-tunnel-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: net-vault-backend
    kind: SecretStore
  target:
    name: cf-tunnel-secret
  data:
    - secretKey: credentials.json
      remoteRef:
        key: networking/cloudflare_tunnel
        property: tunnel-credentials
