apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yml
- deployment.yml
- service.yml
- ingress.yml

commonLabels:
  app: landing
  tier: frontent

images:
- name: nooblearn2code/landing
  newName: nooblearn2code/landing
  newTag: 5889012c
