---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-mysql-pvc
  namespace: seafile
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-pvc
  namespace: seafile
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
  volumeName: seafile-pv
