---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-mysql-pvc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data-pvc
  namespace: seafile
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: data-pool-sc
  resources:
    requests:
      storage: 100Gi
  volumeName: seafile-data-pv
