apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-es
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: auth-service-secret # Tên của cái K8s Secret nó sẽ tự đẻ ra
  dataFrom:
    - extract:
        key: auth-service-secrets # Tên secret bro vừa tạo trên Vault UI
