apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-es
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: shared-vault-backend
    kind: SecretStore
  target:
    name: auth-service-secret
  dataFrom:
    - extract:
        key: auth-service
