apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - ingress.yml
  - secret.yml
  - external-secret.yml

# namePrefix: auth-service-

commonLabels:
  app: auth-service
  tier: backend
# # Sửa Image mà không cần mở file deployment.yaml gốc
# images:
#   - name: my-app-image
#     newName: ghcr.io/nagih7/auth-service
#     newTag: v1.2.3
