---
all:
  children:
    k8s_cluster:
      children:
        k8s_master:
          hosts:
            k8s-master-1: { ansible_host: 192.168.1.201 }

        k8s_worker:
          hosts:
            k8s-worker-1: { ansible_host: 192.168.1.211 }
            k8s-worker-2: { ansible_host: 14.225.218.83 }

    gaming:
      hosts:
        minecraft-server: { ansible_host: 192.168.1.51 }
