apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-tls-cert
  namespace: gitlab
spec:
  secretName: gitlab-tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - gitlab.nooblearn2code.com
