apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gitlab-vault-backend
    kind: SecretStore
  target:
    name: gitlab-secret
  data:
    - secretKey: GITLAB_OMNIBUS_CONFIG
      remoteRef:
        key: tooling/gitlab
        property: omnibus-config
