---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tool-vault-sa
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitlab-vault-backend
spec:
  provider:
    vault:
      server: "http://hashicorp-vault.vault.svc.cluster.local:8200"
      path: "platform"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "tool-role"
          serviceAccountRef:
            name: "tool-vault-sa"
