---
# Seafile
#seafile_mount_path: "{{ data_pool_path }}/seafile"
#seafile_pv: seafile-pv
#seafile_storage: 100Gi
#
## Persistent Volumes
#persistent_volumes:
#  - {
#      name: "{{ seafile_pv }}",
#      storage: "{{ seafile_storage }}",
#      policy: "Retain",
#      class: "local-path",
#      path: "{{ seafile_mount_path }}",
#      node: "k8s-worker-1",
#    }
