apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traefik-dashboard-auth
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infra-vault-backend
    kind: ClusterSecretStore
  target:
    name: traefik-dashboard-secret
  data:
    - secretKey: users
      remoteRef:
        key: traefik
        property: dashboard-htpasswd
