apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traefik-es
  namespace: traefik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: traefik-vault-backend
    kind: SecretStore
  target:
    name: traefik-secret
  data:
    - secretKey: users
      remoteRef:
        key: networking/traefik
        property: dashboard-htpasswd
