apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: shared-vault-backend
    kind: SecretStore
  target:
    name: vaultwarden-secret
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: secret/data/vaultwarden
        property: admin_token
