apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infra-vault-backend
    kind: ClusterSecretStore
  target:
    name: tunnel-credentials-secret
  data:
    - secretKey: credentials.json
      remoteRef:
        key: cloudflare
        property: tunnel-credentials
