apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-bot-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: discord-vault-backend
    kind: SecretStore
  target:
    name: discord-bot-3-secret
  data:
    - secretKey: BOT_TOKEN
      remoteRef:
        key: standalone/discord-bots/bot-3
        property: token
    - secretKey: BOT_NAME
      remoteRef:
        key: standalone/discord-bots/bot-3
        property: name
