apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cf-ddns-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: net-vault-backend
    kind: SecretStore
  target:
    name: cf-ddns-secret
  data:
    - secretKey: API_KEY
      remoteRef:
        key: networking/cloudflare_ddns
        property: api_key
