---
- name: Traefik Configuration
  delegate_to: localhost
  become: false
  tags: k8s-traefik
  block:
    - name: Add Traefik Helm repository
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: https://traefik.github.io/charts

    - name: Deploy Traefik Ingress Controller via Helm
      kubernetes.core.helm:
        name: "{{ traefik_name }}"
        chart_ref: traefik/traefik
        release_namespace: "{{ traefik_namespace }}"
        create_namespace: yes
        update_repo_cache: yes
        wait: yes
        values:
          service:
            type: LoadBalancer
          ingressClass:
            enabled: true
            isDefaultClass: true
            name: traefik
          providers:
            kubernetesCRD:
              enabled: true
            kubernetesIngress:
              enabled: true
          ingressRoute:
            dashboard:
              enabled: true

    - name: Create Secret contain Password for Traefik Dashboard (admin:admin)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ traefik_dashboard_secret }}"
            namespace: "{{ traefik_namespace }}"
          type: Opaque
          stringData:
            users: "{{ traefik_dashboard_user }}:{{ traefik_dashboard_pass }}"

    - name: Create Middleware BasicAuth
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: Middleware
          metadata:
            name: "{{ traefik_dashboard_middleware }}"
            namespace: "{{ traefik_namespace }}"
          spec:
            basicAuth:
              secret: "{{ traefik_dashboard_secret }}"

    - name: Create IngressRoute and hook the Dashboard outwards
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: traefik-dashboard
            namespace: {{ traefik_namespace }}
          spec:
            entryPoints:
              - web
            routes:
              - match: Host(`traefik.{{ base_domain }}`)
                kind: Rule
                services:
                  - name: api@internal
                    kind: TraefikService
                middlewares:
                  - name: {{ traefik_dashboard_middleware }}
