apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-es
  namespace: microservices
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: ms-vault-backend
    kind: SecretStore
  target:
    name: auth-service-secret
  dataFrom:
    - extract:
        key: microservices/auth-service
