---
- name: Shared Service Bootstrap
  include_tasks: bootstrap.yml
  tags: k8s-shared-bootstrap

- name: Postgres Configuration
  include_tasks: postgres.yml
  tags: k8s-postgres

- name: Redis Configuration
  include_tasks: redis.yml
  tags: k8s-redis
