---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: net-vault-sa
  namespace: networking
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: net-vault-backend
  namespace: networking
spec:
  provider:
    vault:
      server: "http://hashicorp-vault.vault.svc.cluster.local:8200"
      path: "infrastructure"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "networking-role"
          serviceAccountRef:
            name: "net-vault-sa"
