apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-config-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: shared-services-vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-omnibus-secret
  data:
    - secretKey: GITLAB_OMNIBUS_CONFIG
      remoteRef:
        key: gitlab
        property: omnibus-config
