apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: db-vault-backend
    kind: SecretStore
  target:
    name: redis-secret
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: databases/redis
        property: password
